export interface PhoneCode {
    name: string;
    flag: string;
    code: string;
    mask: string;
    dialCode: number;
}

export const PhoneCodes: PhoneCode[] = [
    {
        name: "United States",
        flag: "🇺🇸",
        code: "US",
        mask: "(999) 999-9999",
        dialCode: 1,
    },
    {
        name: "Russia",
        flag: "🇷🇺",
        code: "RU",
        mask: "9 (999) 999-99-99",
        dialCode: 7,
    },
    {
        name: "Egypt",
        flag: "🇪🇬",
        code: "EG",
        mask: "9999 999 9999",
        dialCode: 20,
    },
    {
        name: "South Africa",
        flag: "🇿🇦",
        code: "ZA",
        mask: "999 999 9999",
        dialCode: 27,
    },
    {
        name: "Greece",
        flag: "🇬🇷",
        code: "GR",
        mask: "999 999 9999",
        dialCode: 30,
    },
    {
        name: "Netherlands",
        flag: "🇳🇱",
        code: "NL",
        mask: "99 999 999",
        dialCode: 31,
    },
    {
        name: "Belgium",
        flag: "🇧🇪",
        code: "BE",
        mask: "9999 99 99 99",
        dialCode: 32,
    },
    {
        name: "France",
        flag: "🇫🇷",
        code: "FR",
        mask: "99 99 99 99 99",
        dialCode: 33,
    },
    {
        name: "Spain",
        flag: "🇪🇸",
        code: "ES",
        mask: "999 99 99 99",
        dialCode: 34,
    },
    {
        name: "Hungary",
        flag: "🇭🇺",
        code: "HU",
        mask: "(99) 999 9999",
        dialCode: 36,
    },
    {
        name: "Italy",
        flag: "🇮🇹",
        code: "IT",
        mask: "999 999 9999",
        dialCode: 39,
    },
    {
        name: "Romania",
        flag: "🇷🇴",
        code: "RO",
        mask: "9999 999 999",
        dialCode: 40,
    },
    {
        name: "Switzerland",
        flag: "🇨🇭",
        code: "CH",
        mask: "999 999 99 99",
        dialCode: 41,
    },
    {
        name: "Ausesia",
        flag: "🇦🇹",
        code: "AT",
        mask: "9999 999999",
        dialCode: 43,
    },
    {
        name: "Guernsey",
        flag: "🇬🇬",
        code: "GG",
        mask: "99999 999999",
        dialCode: 44,
    },
    {
        name: "Isle of Man",
        flag: "🇮🇲",
        code: "IM",
        mask: "99999 999999",
        dialCode: 44,
    },
    {
        name: "Jersey",
        flag: "🇯🇪",
        code: "JE",
        mask: "99999 999999",
        dialCode: 44,
    },
    {
        name: "United Kingdom",
        flag: "🇬🇧",
        code: "GB",
        mask: "99999 999999",
        dialCode: 44,
    },
    {
        name: "Denmark",
        flag: "🇩🇰",
        code: "DK",
        mask: "99 99 99 99",
        dialCode: 45,
    },
    {
        name: "Sweden",
        flag: "🇸🇪",
        code: "SE",
        mask: "999-999 99 99",
        dialCode: 46,
    },
    {
        name: "Bouvet Island",
        flag: "🇧🇻",
        code: "BV",
        mask: "(99) 99999-9999",
        dialCode: 47,
    },
    {
        name: "Norway",
        flag: "🇳🇴",
        code: "NO",
        mask: "999 99 999",
        dialCode: 47,
    },
    {
        name: "Svalbard and Jan Mayen",
        flag: "🇸🇯",
        code: "SJ",
        mask: "999 99 999",
        dialCode: 47,
    },
    {
        name: "Poland",
        flag: "🇵🇱",
        code: "PL",
        mask: "999 999 999",
        dialCode: 48,
    },
    {
        name: "Germany",
        flag: "🇩🇪",
        code: "DE",
        mask: "99999 9999999",
        dialCode: 49,
    },
    {
        name: "Peru",
        flag: "🇵🇪",
        code: "PE",
        mask: "999 999 999",
        dialCode: 51,
    },
    {
        name: "Mexico",
        flag: "🇲🇽",
        code: "MX",
        mask: "999 999 999 9999",
        dialCode: 52,
    },
    {
        name: "Cuba",
        flag: "🇨🇺",
        code: "CU",
        mask: "99 9999999",
        dialCode: 53,
    },
    {
        name: "Argentina",
        flag: "🇦🇷",
        code: "AR",
        mask: "999 99-9999-9999",
        dialCode: 54,
    },
    {
        name: "Brazil",
        flag: "🇧🇷",
        code: "BR",
        mask: "(99) 99999 9999",
        dialCode: 55,
    },
    {
        name: "Chile",
        flag: "🇨🇱",
        code: "CL",
        mask: "(9) 9999 9999",
        dialCode: 56,
    },
    {
        name: "Colombia",
        flag: "🇨🇴",
        code: "CO",
        mask: "999 9999999",
        dialCode: 57,
    },
    {
        name: "Venezuela, Bolivarian Republic of Venezuela",
        flag: "🇻🇪",
        code: "VE",
        mask: "9999-9999999",
        dialCode: 58,
    },
    {
        name: "Malaysia",
        flag: "🇲🇾",
        code: "MY",
        mask: "999-999 9999",
        dialCode: 60,
    },
    {
        name: "Ausesalia",
        flag: "🇦🇺",
        code: "AU",
        mask: "9999 999 999",
        dialCode: 61,
    },
    {
        name: "Christmas Island",
        flag: "🇨🇽",
        code: "CX",
        mask: "9999 999 999",
        dialCode: 61,
    },
    {
        name: "Cocos (Keeling) Islands",
        flag: "🇨🇨",
        code: "CC",
        mask: "9999 999 999",
        dialCode: 61,
    },
    {
        name: "Indonesia",
        flag: "🇮🇩",
        code: "ID",
        mask: "9999-999-999",
        dialCode: 62,
    },
    {
        name: "Philippines",
        flag: "🇵🇭",
        code: "PH",
        mask: "9999 999 9999",
        dialCode: 63,
    },
    {
        name: "New Zealand",
        flag: "🇳🇿",
        code: "NZ",
        mask: "999 999 9999",
        dialCode: 64,
    },
    {
        name: "Singapore",
        flag: "🇸🇬",
        code: "SG",
        mask: "9999 9999",
        dialCode: 65,
    },
    {
        name: "Thailand",
        flag: "🇹🇭",
        code: "TH",
        mask: "999 999 9999",
        dialCode: 66,
    },
    {
        name: "Japan",
        flag: "🇯🇵",
        code: "JP",
        mask: "999-9999-9999",
        dialCode: 81,
    },
    {
        name: "Korea, Republic of South Korea",
        flag: "🇰🇷",
        code: "KR",
        mask: "999-9999-9999",
        dialCode: 82,
    },
    {
        name: "Vietnam",
        flag: "🇻🇳",
        code: "VN",
        mask: "999 999 99 99",
        dialCode: 84,
    },
    {
        name: "China",
        flag: "🇨🇳",
        code: "CN",
        mask: "999 9999 9999",
        dialCode: 86,
    },
    {
        name: "Turkey",
        flag: "🇹🇷",
        code: "es",
        mask: "(999) 999 9999",
        dialCode: 90,
    },
    {
        name: "India",
        flag: "🇮🇳",
        code: "IN",
        mask: "99999 99999",
        dialCode: 91,
    },
    {
        name: "Pakistan",
        flag: "🇵🇰",
        code: "PK",
        mask: "9999 9999999",
        dialCode: 92,
    },
    {
        name: "Afghanistan",
        flag: "🇦🇫",
        code: "AF",
        mask: "999 999 9999",
        dialCode: 93,
    },
    {
        name: "Sri Lanka",
        flag: "🇱🇰",
        code: "LK",
        mask: "999 999 9999",
        dialCode: 94,
    },
    {
        name: "Myanmar",
        flag: "🇲🇲",
        code: "MM",
        mask: "99 999 9999",
        dialCode: 95,
    },
    {
        name: "Iran, Islamic Republic of Persian Gulf",
        flag: "🇮🇷",
        code: "IR",
        mask: "9999 999 9999",
        dialCode: 98,
    },
    {
        name: "South Sudan",
        flag: "🇸🇸",
        code: "SS",
        mask: "9999 999 999",
        dialCode: 211,
    },
    {
        name: "Morocco",
        flag: "🇲🇦",
        code: "MA",
        mask: "9999-999999",
        dialCode: 212,
    },
    {
        name: "Algeria",
        flag: "🇩🇿",
        code: "DZ",
        mask: "9999 99 99 99",
        dialCode: 213,
    },
    {
        name: "Tunisia",
        flag: "🇹🇳",
        code: "TN",
        mask: "99 999 999",
        dialCode: 216,
    },
    {
        name: "Libyan Arab Jamahiriya",
        flag: "🇱🇾",
        code: "LY",
        mask: "999-9999999",
        dialCode: 218,
    },
    {
        name: "Gambia",
        flag: "🇬🇲",
        code: "GM",
        mask: "999 9999",
        dialCode: 220,
    },
    {
        name: "Senegal",
        flag: "🇸🇳",
        code: "SN",
        mask: "99 999 99 99",
        dialCode: 221,
    },
    {
        name: "Mauritania",
        flag: "🇲🇷",
        code: "MR",
        mask: "99 99 99 99",
        dialCode: 222,
    },
    {
        name: "Mali",
        flag: "🇲🇱",
        code: "ML",
        mask: "99 99 99 99",
        dialCode: 223,
    },
    {
        name: "Guinea",
        flag: "🇬🇳",
        code: "GN",
        mask: "999 99 99 99",
        dialCode: 224,
    },
    {
        name: "Cote d'Ivoire",
        flag: "🇨🇮",
        code: "CI",
        mask: "99 99 99 99",
        dialCode: 225,
    },
    {
        name: "Burkina Faso",
        flag: "🇧🇫",
        code: "BF",
        mask: "99 99 99 99",
        dialCode: 226,
    },
    {
        name: "Niger",
        flag: "🇳🇪",
        code: "NE",
        mask: "99 99 99 99",
        dialCode: 227,
    },
    {
        name: "Togo",
        flag: "🇹🇬",
        code: "TG",
        mask: "99 99 99 99",
        dialCode: 228,
    },
    {
        name: "Benin",
        flag: "🇧🇯",
        code: "BJ",
        mask: "99 99 99 99",
        dialCode: 229,
    },
    {
        name: "Mauritius",
        flag: "🇲🇺",
        code: "MU",
        mask: "9999 9999",
        dialCode: 230,
    },
    {
        name: "Liberia",
        flag: "🇱🇷",
        code: "LR",
        mask: "999 999 9999",
        dialCode: 231,
    },
    {
        name: "Sierra Leone",
        flag: "🇸🇱",
        code: "SL",
        mask: "(999) 999999",
        dialCode: 232,
    },
    {
        name: "Ghana",
        flag: "🇬🇭",
        code: "GH",
        mask: "999 999 9999",
        dialCode: 233,
    },
    {
        name: "Nigeria",
        flag: "🇳🇬",
        code: "NG",
        mask: "9999 999 9999",
        dialCode: 234,
    },
    {
        name: "Chad",
        flag: "🇹🇩",
        code: "TD",
        mask: "99 99 99 99",
        dialCode: 235,
    },
    {
        name: "Cenesal African Republic",
        flag: "🇨🇫",
        code: "CF",
        mask: "99 99 99 99",
        dialCode: 236,
    },
    {
        name: "Cameroon",
        flag: "🇨🇲",
        code: "CM",
        mask: "9 99 99 99 99",
        dialCode: 237,
    },
    {
        name: "Cape Verde",
        flag: "🇨🇻",
        code: "CV",
        mask: "999 99 99",
        dialCode: 238,
    },
    {
        name: "Sao Tome and Principe",
        flag: "🇸🇹",
        code: "ST",
        mask: "999 9999",
        dialCode: 239,
    },
    {
        name: "Equatorial Guinea",
        flag: "🇬🇶",
        code: "GQ",
        mask: "999 999 999",
        dialCode: 240,
    },
    {
        name: "Gabon",
        flag: "🇬🇦",
        code: "GA",
        mask: "99 99 99 99",
        dialCode: 241,
    },
    {
        name: "Congo",
        flag: "🇨🇬",
        code: "CG",
        mask: "9999 999 999",
        dialCode: 242,
    },
    {
        name: "Congo, The Democratic Republic of the Congo",
        flag: "🇨🇩",
        code: "CD",
        mask: "99 999 9999",
        dialCode: 243,
    },
    {
        name: "Angola",
        flag: "🇦🇴",
        code: "AO",
        mask: "999 999 999",
        dialCode: 244,
    },
    {
        name: "Guinea-Bissau",
        flag: "🇬🇼",
        code: "GW",
        mask: "999 999 999",
        dialCode: 245,
    },
    {
        name: "British Indian Ocean Territory",
        flag: "🇮🇴",
        code: "IO",
        mask: "(999) 999-9999",
        dialCode: 246,
    },
    {
        name: "Seychelles",
        flag: "🇸🇨",
        code: "SC",
        mask: "9 999 999",
        dialCode: 248,
    },
    {
        name: "Sudan",
        flag: "🇸🇩",
        code: "SD",
        mask: "999 999 9999",
        dialCode: 249,
    },
    {
        name: "Rwanda",
        flag: "🇷🇼",
        code: "RW",
        mask: "9999 999 999",
        dialCode: 250,
    },
    {
        name: "Ethiopia",
        flag: "🇪🇹",
        code: "ET",
        mask: "999 999 9999",
        dialCode: 251,
    },
    {
        name: "Somalia",
        flag: "🇸🇴",
        code: "SO",
        mask: "9 9999999",
        dialCode: 252,
    },
    {
        name: "Djibouti",
        flag: "🇩🇯",
        code: "DJ",
        mask: "99 99 99 99",
        dialCode: 253,
    },
    {
        name: "Kenya",
        flag: "🇰🇪",
        code: "KE",
        mask: "9999 999999",
        dialCode: 254,
    },
    {
        name: "Tanzania, United Republic of Tanzania",
        flag: "🇹🇿",
        code: "TZ",
        mask: "9999 999 999",
        dialCode: 255,
    },
    {
        name: "Uganda",
        flag: "🇺🇬",
        code: "UG",
        mask: "9999 999999",
        dialCode: 256,
    },
    {
        name: "Burundi",
        flag: "🇧🇮",
        code: "BI",
        mask: "99 99 99 99",
        dialCode: 257,
    },
    {
        name: "Mozambique",
        flag: "🇲🇿",
        code: "MZ",
        mask: "99 999 9999",
        dialCode: 258,
    },
    {
        name: "Zambia",
        flag: "🇿🇲",
        code: "ZM",
        mask: "999 9999999",
        dialCode: 260,
    },
    {
        name: "Madagascar",
        flag: "🇲🇬",
        code: "MG",
        mask: "999 99 999 99",
        dialCode: 261,
    },
    {
        name: "Mayotte",
        flag: "🇾🇹",
        code: "YT",
        mask: "9999 99 99 99",
        dialCode: 262,
    },
    {
        name: "Zimbabwe",
        flag: "🇿🇼",
        code: "ZW",
        mask: "999 999 9999",
        dialCode: 263,
    },
    {
        name: "Namibia",
        flag: "🇳🇦",
        code: "NA",
        mask: "999 999 99999",
        dialCode: 264,
    },
    {
        name: "Malawi",
        flag: "🇲🇼",
        code: "MW",
        mask: "9999 99 99 99",
        dialCode: 265,
    },
    {
        name: "Lesotho",
        flag: "🇱🇸",
        code: "LS",
        mask: "9999 9999",
        dialCode: 266,
    },
    {
        name: "Botswana",
        flag: "🇧🇼",
        code: "BW",
        mask: "99 999 999",
        dialCode: 267,
    },
    {
        name: "Swaziland",
        flag: "🇸🇿",
        code: "SZ",
        mask: "9999 9999",
        dialCode: 268,
    },
    {
        name: "Comoros",
        flag: "🇰🇲",
        code: "KM",
        mask: "999 99 99",
        dialCode: 269,
    },
    {
        name: "Saint Helena, Ascension and esistan Da Cunha",
        flag: "🇸🇭",
        code: "SH",
        mask: "99999",
        dialCode: 290,
    },
    {
        name: "Eriesea",
        flag: "🇪🇷",
        code: "ER",
        mask: "99 999 999",
        dialCode: 291,
    },
    {
        name: "Aruba",
        flag: "🇦🇼",
        code: "AW",
        mask: "999 9999",
        dialCode: 297,
    },
    {
        name: "Faroe Islands",
        flag: "🇫🇴",
        code: "FO",
        mask: "999999",
        dialCode: 298,
    },
    {
        name: "Greenland",
        flag: "🇬🇱",
        code: "GL",
        mask: "99 99 99",
        dialCode: 299,
    },
    {
        name: "Cayman Islands",
        flag: "🇰🇾",
        code: "KY",
        mask: "999 9999",
        dialCode: 345,
    },
    {
        name: "Gibraltar",
        flag: "🇬🇮",
        code: "GI",
        mask: "99999999",
        dialCode: 350,
    },
    {
        name: "Portugal",
        flag: "🇵🇹",
        code: "PT",
        mask: "999 999 999",
        dialCode: 351,
    },
    {
        name: "Luxembourg",
        flag: "🇱🇺",
        code: "LU",
        mask: "999 999 999",
        dialCode: 352,
    },
    {
        name: "Ireland",
        flag: "🇮🇪",
        code: "IE",
        mask: "999 999 9999",
        dialCode: 353,
    },
    {
        name: "Iceland",
        flag: "🇮🇸",
        code: "IS",
        mask: "999 9999",
        dialCode: 354,
    },
    {
        name: "Albania",
        flag: "🇦🇱",
        code: "AL",
        mask: "999 999 9999",
        dialCode: 355,
    },
    {
        name: "Malta",
        flag: "🇲🇹",
        code: "MT",
        mask: "9999 9999",
        dialCode: 356,
    },
    {
        name: "Cyprus",
        flag: "🇨🇾",
        code: "CY",
        mask: "99 999999",
        dialCode: 357,
    },
    {
        name: "Åland Islands",
        flag: "🇦🇽",
        code: "AX",
        mask: "999 9999999",
        dialCode: 358,
    },
    {
        name: "Finland",
        flag: "🇫🇮",
        code: "FI",
        mask: "999 9999999",
        dialCode: 358,
    },
    {
        name: "Bulgaria",
        flag: "🇧🇬",
        code: "BG",
        mask: "999 999 999",
        dialCode: 359,
    },
    {
        name: "Lithuania",
        flag: "🇱🇹",
        code: "LT",
        mask: "(9-999) 9999",
        dialCode: 370,
    },
    {
        name: "Latvia",
        flag: "🇱🇻",
        code: "LV",
        mask: "99 999 999",
        dialCode: 371,
    },
    {
        name: "Estonia",
        flag: "🇪🇪",
        code: "EE",
        mask: "9999 9999",
        dialCode: 372,
    },
    {
        name: "Moldova",
        flag: "🇲🇩",
        code: "MD",
        mask: "9999 99 999",
        dialCode: 373,
    },
    {
        name: "Armenia",
        flag: "🇦🇲",
        code: "AM",
        mask: "999 999999",
        dialCode: 374,
    },
    {
        name: "Belarus",
        flag: "🇧🇾",
        code: "BY",
        mask: "9 999 999-99-99",
        dialCode: 375,
    },
    {
        name: "Andorra",
        flag: "🇦🇩",
        code: "AD",
        mask: "999 999",
        dialCode: 376,
    },
    {
        name: "Monaco",
        flag: "🇲🇨",
        code: "MC",
        mask: "99 99 99 99 99",
        dialCode: 377,
    },
    {
        name: "San Marino",
        flag: "🇸🇲",
        code: "SM",
        mask: "99 99 99 99",
        dialCode: 378,
    },
    {
        name: "Ukraine",
        flag: "🇺🇦",
        code: "UA",
        mask: "999 999 9999",
        dialCode: 380,
    },
    {
        name: "Serbia",
        flag: "🇷🇸",
        code: "RS",
        mask: "999 9999999",
        dialCode: 381,
    },
    {
        name: "Montenegro",
        flag: "🇲🇪",
        code: "ME",
        mask: "999 999 999",
        dialCode: 382,
    },
    {
        name: "Kosovo",
        flag: "🇽🇰",
        code: "XK",
        mask: "999 999 999",
        dialCode: 383,
    },
    {
        name: "Croatia",
        flag: "🇭🇷",
        code: "HR",
        mask: "999 999 9999",
        dialCode: 385,
    },
    {
        name: "Slovenia",
        flag: "🇸🇮",
        code: "SI",
        mask: "999 999 999",
        dialCode: 386,
    },
    {
        name: "Bosnia and Herzegovina",
        flag: "🇧🇦",
        code: "BA",
        mask: "999 999 999",
        dialCode: 387,
    },
    {
        name: "Macedonia",
        flag: "🇲🇰",
        code: "MK",
        mask: "999 999 999",
        dialCode: 389,
    },
    {
        name: "Czech Republic",
        flag: "🇨🇿",
        code: "CZ",
        mask: "999 999 999",
        dialCode: 420,
    },
    {
        name: "Slovakia",
        flag: "🇸🇰",
        code: "SK",
        mask: "9999 999 999",
        dialCode: 421,
    },
    {
        name: "Liechtenstein",
        flag: "🇱🇮",
        code: "LI",
        mask: "999 999 999",
        dialCode: 423,
    },
    {
        name: "Falkland Islands (Malvinas)",
        flag: "🇫🇰",
        code: "FK",
        mask: "99999",
        dialCode: 500,
    },
    {
        name: "Belize",
        flag: "🇧🇿",
        code: "BZ",
        mask: "999-9999",
        dialCode: 501,
    },
    {
        name: "Guatemala",
        flag: "🇬🇹",
        code: "GT",
        mask: "9999 9999",
        dialCode: 502,
    },
    {
        name: "El Salvador",
        flag: "🇸🇻",
        code: "SV",
        mask: "9999 9999",
        dialCode: 503,
    },
    {
        name: "Honduras",
        flag: "🇭🇳",
        code: "HN",
        mask: "9999-9999",
        dialCode: 504,
    },
    {
        name: "Nicaragua",
        flag: "🇳🇮",
        code: "NI",
        mask: "9999 9999",
        dialCode: 505,
    },
    {
        name: "Costa Rica",
        flag: "🇨🇷",
        code: "CR",
        mask: "9999 9999",
        dialCode: 506,
    },
    {
        name: "Panama",
        flag: "🇵🇦",
        code: "PA",
        mask: "9999-9999",
        dialCode: 507,
    },
    {
        name: "Saint Pierre and Miquelon",
        flag: "🇵🇲",
        code: "PM",
        mask: "999 99 99",
        dialCode: 508,
    },
    {
        name: "Haiti",
        flag: "🇭🇹",
        code: "HT",
        mask: "99 99 9999",
        dialCode: 509,
    },
    {
        name: "Guadeloupe",
        flag: "🇬🇵",
        code: "GP",
        mask: "9999 99 99 99",
        dialCode: 590,
    },
    {
        name: "Saint Barthelemy",
        flag: "🇧🇱",
        code: "BL",
        mask: "9999 99 99 99",
        dialCode: 590,
    },
    {
        name: "Saint Martin",
        flag: "🇲🇫",
        code: "MF",
        mask: "9999 99 99 99",
        dialCode: 590,
    },
    {
        name: "Bolivia",
        flag: "🇧🇴",
        code: "BO",
        mask: "99999999",
        dialCode: 591,
    },
    {
        name: "Guyana",
        flag: "🇬🇾",
        code: "GY",
        mask: "999 9999",
        dialCode: 592,
    },
    {
        name: "Ecuador",
        flag: "🇪🇨",
        code: "EC",
        mask: "999 999 9999",
        dialCode: 593,
    },
    {
        name: "French Guiana",
        flag: "🇬🇫",
        code: "GF",
        mask: "9999 99 99 99",
        dialCode: 594,
    },
    {
        name: "Paraguay",
        flag: "🇵🇾",
        code: "PY",
        mask: "9999 999999",
        dialCode: 595,
    },
    {
        name: "Martinique",
        flag: "🇲🇶",
        code: "MQ",
        mask: "9999 99 99 99",
        dialCode: 596,
    },
    {
        name: "Suriname",
        flag: "🇸🇷",
        code: "SR",
        mask: "999-9999",
        dialCode: 597,
    },
    {
        name: "Uruguay",
        flag: "🇺🇾",
        code: "UY",
        mask: "999 999 999",
        dialCode: 598,
    },
    {
        name: "Timor-Leste",
        flag: "🇹🇱",
        code: "TL",
        mask: "9999 9999",
        dialCode: 670,
    },
    {
        name: "Norfolk Island",
        flag: "🇳🇫",
        code: "NF",
        mask: "9 99999",
        dialCode: 672,
    },
    {
        name: "Brunei Darussalam",
        flag: "🇧🇳",
        code: "BN",
        mask: "999 9999",
        dialCode: 673,
    },
    {
        name: "Nauru",
        flag: "🇳🇷",
        code: "NR",
        mask: "999 9999",
        dialCode: 674,
    },
    {
        name: "Papua New Guinea",
        flag: "🇵🇬",
        code: "PG",
        mask: "9999 9999",
        dialCode: 675,
    },
    {
        name: "Tonga",
        flag: "🇹🇴",
        code: "TO",
        mask: "999 9999",
        dialCode: 676,
    },
    {
        name: "Solomon Islands",
        flag: "🇸🇧",
        code: "SB",
        mask: "99 99999",
        dialCode: 677,
    },
    {
        name: "Vanuatu",
        flag: "🇻🇺",
        code: "VU",
        mask: "999 9999",
        dialCode: 678,
    },
    {
        name: "Fiji",
        flag: "🇫🇯",
        code: "FJ",
        mask: "999 9999",
        dialCode: 679,
    },
    {
        name: "Palau",
        flag: "🇵🇼",
        code: "PW",
        mask: "999 9999",
        dialCode: 680,
    },
    {
        name: "Wallis and Futuna",
        flag: "🇼🇫",
        code: "WF",
        mask: "99 99 99",
        dialCode: 681,
    },
    {
        name: "Cook Islands",
        flag: "🇨🇰",
        code: "CK",
        mask: "99 999",
        dialCode: 682,
    },
    {
        name: "Niue",
        flag: "🇳🇺",
        code: "NU",
        mask: "999 9999",
        dialCode: 683,
    },
    {
        name: "Samoa",
        flag: "🇼🇸",
        code: "WS",
        mask: "99 99999",
        dialCode: 685,
    },
    {
        name: "Kiribati",
        flag: "🇰🇮",
        code: "KI",
        mask: "99999999",
        dialCode: 686,
    },
    {
        name: "New Caledonia",
        flag: "🇳🇨",
        code: "NC",
        mask: "99.99.99",
        dialCode: 687,
    },
    {
        name: "Tuvalu",
        flag: "🇹🇻",
        code: "TV",
        mask: "999999",
        dialCode: 688,
    },
    {
        name: "French Polynesia",
        flag: "🇵🇫",
        code: "PF",
        mask: "99 99 99 99",
        dialCode: 689,
    },
    {
        name: "Tokelau",
        flag: "🇹🇰",
        code: "TK",
        mask: "9999",
        dialCode: 690,
    },
    {
        name: "Micronesia, Federated States of Micronesia",
        flag: "🇫🇲",
        code: "FM",
        mask: "999 9999",
        dialCode: 691,
    },
    {
        name: "Marshall Islands",
        flag: "🇲🇭",
        code: "MH",
        mask: "999-9999",
        dialCode: 692,
    },
    {
        name: "Korea, Democratic People's Republic of Korea",
        flag: "🇰🇵",
        code: "KP",
        mask: "(9) 99999",
        dialCode: 850,
    },
    {
        name: "Hong Kong",
        flag: "🇭🇰",
        code: "HK",
        mask: "9999 9999",
        dialCode: 852,
    },
    {
        name: "Macao",
        flag: "🇲🇴",
        code: "MO",
        mask: "9999 9999",
        dialCode: 853,
    },
    {
        name: "Cambodia",
        flag: "🇰🇭",
        code: "KH",
        mask: "999 999 999",
        dialCode: 855,
    },
    {
        name: "Laos",
        flag: "🇱🇦",
        code: "LA",
        mask: "999 99 999 999",
        dialCode: 856,
    },
    {
        name: "Bangladesh",
        flag: "🇧🇩",
        code: "BD",
        mask: "99999-999999",
        dialCode: 880,
    },
    {
        name: "Taiwan",
        flag: "🇹🇼",
        code: "TW",
        mask: "9999 999 999",
        dialCode: 886,
    },
    {
        name: "Maldives",
        flag: "🇲🇻",
        code: "MV",
        mask: "999-9999",
        dialCode: 960,
    },
    {
        name: "Lebanon",
        flag: "🇱🇧",
        code: "LB",
        mask: "99 999 999",
        dialCode: 961,
    },
    {
        name: "Jordan",
        flag: "🇯🇴",
        code: "JO",
        mask: "99 9999 9999",
        dialCode: 962,
    },
    {
        name: "Syrian Arab Republic",
        flag: "🇸🇾",
        code: "SY",
        mask: "9999 999 999",
        dialCode: 963,
    },
    {
        name: "Iraq",
        flag: "🇮🇶",
        code: "IQ",
        mask: "9999 999 9999",
        dialCode: 964,
    },
    {
        name: "Kuwait",
        flag: "🇰🇼",
        code: "KW",
        mask: "999 99999",
        dialCode: 965,
    },
    {
        name: "Saudi Arabia",
        flag: "🇸🇦",
        code: "SA",
        mask: "999 999 9999",
        dialCode: 966,
    },
    {
        name: "Yemen",
        flag: "🇾🇪",
        code: "YE",
        mask: "999 999 999",
        dialCode: 967,
    },
    {
        name: "Oman",
        flag: "🇴🇲",
        code: "OM",
        mask: "9999 9999",
        dialCode: 968,
    },
    {
        name: "Palestinian Territory, Occupied",
        flag: "🇵🇸",
        code: "PS",
        mask: "9999 999 999",
        dialCode: 970,
    },
    {
        name: "United Arab Emirates",
        flag: "🇦🇪",
        code: "AE",
        mask: "999 999 9999",
        dialCode: 971,
    },
    {
        name: "Israel",
        flag: "🇮🇱",
        code: "IL",
        mask: "999-999-9999",
        dialCode: 972,
    },
    {
        name: "Bahrain",
        flag: "🇧🇭",
        code: "BH",
        mask: "9999 9999",
        dialCode: 973,
    },
    {
        name: "Qatar",
        flag: "🇶🇦",
        code: "QA",
        mask: "9999 9999",
        dialCode: 974,
    },
    {
        name: "Bhutan",
        flag: "🇧🇹",
        code: "BT",
        mask: "99 99 99 99",
        dialCode: 975,
    },
    {
        name: "Mongolia",
        flag: "🇲🇳",
        code: "MN",
        mask: "9999 9999",
        dialCode: 976,
    },
    {
        name: "Nepal",
        flag: "🇳🇵",
        code: "NP",
        mask: "999-9999999",
        dialCode: 977,
    },
    {
        name: "Tajikistan",
        flag: "🇹🇯",
        code: "TJ",
        mask: "999 99 9999",
        dialCode: 992,
    },
    {
        name: "Turkmenistan",
        flag: "🇹🇲",
        code: "TM",
        mask: "9 99 999999",
        dialCode: 993,
    },
    {
        name: "Azerbaijan",
        flag: "🇦🇿",
        code: "AZ",
        mask: "999 999 99 99",
        dialCode: 994,
    },
    {
        name: "Georgia",
        flag: "🇬🇪",
        code: "GE",
        mask: "999 99 99 99",
        dialCode: 995,
    },
    {
        name: "Kyrgyzstan",
        flag: "🇰🇬",
        code: "KG",
        mask: "9999 999 999",
        dialCode: 996,
    },
    {
        name: "Uzbekistan",
        flag: "🇺🇿",
        code: "UZ",
        mask: "9 99 999 99 99",
        dialCode: 998,
    },
    {
        name: "Bahamas",
        flag: "🇧🇸",
        code: "BS",
        mask: "(999) 999-999",
        dialCode: 1242,
    },
    {
        name: "Barbados",
        flag: "🇧🇧",
        code: "BB",
        mask: "(999) 999-9999",
        dialCode: 1246,
    },
    {
        name: "Anguilla",
        flag: "🇦🇮",
        code: "AI",
        mask: "(999) 999-9999",
        dialCode: 1264,
    },
    {
        name: "Antigua and Barbuda",
        flag: "🇦🇬",
        code: "AG",
        mask: "(999) 999-9999",
        dialCode: 1268,
    },
    {
        name: "Bermuda",
        flag: "🇧🇲",
        code: "BM",
        mask: "(999) 999-9999",
        dialCode: 1441,
    },
    {
        name: "Grenada",
        flag: "🇬🇩",
        code: "GD",
        mask: "(999) 999-9999",
        dialCode: 1473,
    },
    {
        name: "Turks and Caicos Islands",
        flag: "🇹🇨",
        code: "TC",
        mask: "(999) 999-9999",
        dialCode: 1649,
    },
    {
        name: "Montserrat",
        flag: "🇲🇸",
        code: "MS",
        mask: "(999) 999-9999",
        dialCode: 1664,
    },
    {
        name: "Northern Mariana Islands",
        flag: "🇲🇵",
        code: "MP",
        mask: "(999) 999-9999",
        dialCode: 1670,
    },
    {
        name: "Guam",
        flag: "🇬🇺",
        code: "GU",
        mask: "(999) 999-9999",
        dialCode: 1671,
    },
    {
        name: "American Samoa",
        flag: "🇦🇸",
        code: "AS",
        mask: "(999) 999-9999",
        dialCode: 1684,
    },
    {
        name: "Saint Lucia",
        flag: "🇱🇨",
        code: "LC",
        mask: "(999) 999-9999",
        dialCode: 1758,
    },
    {
        name: "Dominica",
        flag: "🇩🇲",
        code: "DM",
        mask: "(999) 999-9999",
        dialCode: 1767,
    },
    {
        name: "Saint Vincent and the Grenadines",
        flag: "🇻🇨",
        code: "VC",
        mask: "(999) 999-9999",
        dialCode: 1784,
    },
    {
        name: "esinidad and Tobago",
        flag: "🇹🇹",
        code: "TT",
        mask: "(999) 999-9999",
        dialCode: 1868,
    },
    {
        name: "Saint Kitts and Nevis",
        flag: "🇰🇳",
        code: "KN",
        mask: "(999) 999-9999",
        dialCode: 1869,
    },
    {
        name: "Jamaica",
        flag: "🇯🇲",
        code: "JM",
        mask: "(999) 999-9999",
        dialCode: 1876,
    },
    {
        name: "Puerto Rico",
        flag: "🇵🇷",
        code: "PR",
        mask: "(999) 999-9999",
        dialCode: 1939,
    },
] as const;
