// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

// biome-ignore lint/suspicious/noExplicitAny: <explanation>
export const Index: Record<string, any> = {
    index: {
        name: "index",
        description: "",
        type: "registry:style",
        registryDependencies: ["utils"],
        files: [],
        component: null,
        meta: undefined,
    },
    input: {
        name: "input",
        description: "A input component",
        type: "registry:ui",
        registryDependencies: undefined,
        files: [
            {
                path: "src/registry/ui/input.tsx",
                type: "registry:ui",
                target: "components/wed/input.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/ui/input.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    select: {
        name: "select",
        description: "A select component",
        type: "registry:ui",
        registryDependencies: undefined,
        files: [
            {
                path: "src/registry/ui/select.tsx",
                type: "registry:ui",
                target: "components/wed/select.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/ui/select.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-size-demo": {
        name: "input-size-demo",
        description: "A demo of the input size",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/size.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-size-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/input/size.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-variant-demo": {
        name: "input-variant-demo",
        description: "A demo of the input variant",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/variant.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-variant-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/input/variant.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-disabled-demo": {
        name: "input-disabled-demo",
        description: "A demo of the input disabled",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/disabled.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-disabled-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/input/disabled.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-invalid-demo": {
        name: "input-invalid-demo",
        description: "A demo of the input invalid",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/invalid.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-invalid-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/input/invalid.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-start-end-content-demo": {
        name: "input-start-end-content-demo",
        description: "A demo of the input start end content",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/start-end-content.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-start-end-content-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import(
                "@/registry/example/input/start-end-content.tsx"
            );
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-password-demo": {
        name: "input-password-demo",
        description: "A demo of the input password",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/password.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-password-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/input/password.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-phone-input-demo": {
        name: "input-phone-input-demo",
        description: "A demo of the input phone input",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/phone-input.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-phone-input-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import(
                "@/registry/example/input/phone-input.tsx"
            );
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "input-form-demo": {
        name: "input-form-demo",
        description: "A demo of the input form",
        type: "registry:example",
        registryDependencies: ["https://ui.ednesdayw.com/r/input.json"],
        files: [
            {
                path: "src/registry/example/input/form.tsx",
                type: "registry:example",
                target: "components/wed-demo/input-form-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/input/form.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "select-size-demo": {
        name: "select-size-demo",
        description: "A demo of the select size",
        type: "registry:example",
        registryDependencies: undefined,
        files: [
            {
                path: "src/registry/example/select/size.tsx",
                type: "registry:example",
                target: "components/wed-demo/select-size-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/select/size.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    "select-variant-demo": {
        name: "select-variant-demo",
        description: "A demo of the select variant",
        type: "registry:example",
        registryDependencies: undefined,
        files: [
            {
                path: "src/registry/example/select/variant.tsx",
                type: "registry:example",
                target: "components/wed-demo/select-variant-demo.tsx",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/example/select/variant.tsx");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
    utils: {
        name: "utils",
        description: "",
        type: "registry:lib",
        registryDependencies: undefined,
        files: [
            {
                path: "src/registry/lib/utils.ts",
                type: "registry:lib",
                target: "lib/utils.ts",
            },
        ],
        component: React.lazy(async () => {
            const mod = await import("@/registry/lib/utils.ts");
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof mod[key] === "function" ||
                        typeof mod[key] === "object",
                ) || item.name;
            return { default: mod.default || mod[exportName] };
        }),
        meta: undefined,
    },
};
