export const countries = [
    { key: "cn", label: "China" },
    { key: "jp", label: "Japan" },
    { key: "kr", label: "Korea" },
    { key: "ru", label: "Russia" },
    { key: "in", label: "India" },
    { key: "br", label: "Brazil" },
    { key: "de", label: "Germany" },
    { key: "fr", label: "France" },
    { key: "it", label: "Italy" },
    { key: "es", label: "Spain" },
    { key: "us", label: "United States" },
    { key: "ca", label: "Canada" },
    { key: "mx", label: "Mexico" },
    { key: "gb", label: "United Kingdom" },
    { key: "au", label: "Australia" },
    { key: "nz", label: "New Zealand" },
];
